version: "3"
services:
  rocket-template:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://postgres:@db/diesel_demo"
  db:
    image: postgres:12.6
    ports:
      - 5432
    environment:
      POSTGRES_DB: diesel_demo
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --no-locale"
